services:
  - type: web
    name: inclusive-learning-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: MONGODB_DATABASE_NAME
        value: inclusive_learning
      - key: SECRET_KEY
        generateValue: true
      - key: REFRESH_SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        sync: false

